-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 16:13:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereço` (
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`rua`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `nome` VARCHAR(100) NOT NULL,
  `preço` INT(15) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NULL,
  `endereço_rua` VARCHAR(100) NOT NULL,
  `produto_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nome`),
  INDEX `fk_clientes_endereço_idx` (`endereço_rua` ASC) VISIBLE,
  INDEX `fk_clientes_produto1_idx` (`produto_nome` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_endereço`
    FOREIGN KEY (`endereço_rua`)
    REFERENCES `mydb`.`endereço` (`rua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_produto1`
    FOREIGN KEY (`produto_nome`)
    REFERENCES `mydb`.`produto` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereço_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereço_has_produto` (
  `endereço_rua` VARCHAR(100) NOT NULL,
  `produto_nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`endereço_rua`, `produto_nome`),
  INDEX `fk_endereço_has_produto_produto1_idx` (`produto_nome` ASC) VISIBLE,
  INDEX `fk_endereço_has_produto_endereço1_idx` (`endereço_rua` ASC) VISIBLE,
  CONSTRAINT `fk_endereço_has_produto_endereço1`
    FOREIGN KEY (`endereço_rua`)
    REFERENCES `mydb`.`endereço` (`rua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereço_has_produto_produto1`
    FOREIGN KEY (`produto_nome`)
    REFERENCES `mydb`.`produto` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENDEREÇO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENDEREÇO` (
  `id_ENDEREÇO_Pess/unidade` VARCHAR(10) NOT NULL,
  `RUA` VARCHAR(100) NOT NULL,
  `BAIRRO` VARCHAR(100) NOT NULL,
  `CIDADE` VARCHAR(100) NOT NULL,
  `ESTADO` VARCHAR(100) NOT NULL,
  `CEP` INT(7) NOT NULL,
  PRIMARY KEY (`id_ENDEREÇO_Pess/unidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIDADES` (
  `Id_Unidade` VARCHAR(45) NOT NULL,
  `SALAS` INT(10) NOT NULL,
  `ENDEREÇO_id_ENDEREÇO_Pess/unidade` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Unidade`),
  INDEX `fk_UNIDADES_ENDEREÇO1_idx` (`ENDEREÇO_id_ENDEREÇO_Pess/unidade` ASC) VISIBLE,
  CONSTRAINT `fk_UNIDADES_ENDEREÇO1`
    FOREIGN KEY (`ENDEREÇO_id_ENDEREÇO_Pess/unidade`)
    REFERENCES `mydb`.`ENDEREÇO` (`id_ENDEREÇO_Pess/unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMAS` (
  `id_COD_TURMA` VARCHAR(100) NOT NULL,
  `Dia_da_semana` VARCHAR(100) NOT NULL,
  `SALA` INT(10) NOT NULL,
  `TURNO` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_COD_TURMA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSOS` (
  `id_CURSO_nome` VARCHAR(45) NOT NULL,
  `Carga_horária` VARCHAR(40) NOT NULL,
  `Preço` VARCHAR(40) NOT NULL,
  `UNIDADES_id_UNIDADES` VARCHAR(45) NOT NULL,
  `TURMAS_id_COD_TURMA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_CURSO_nome`),
  INDEX `fk_CURSOS_UNIDADES1_idx` (`UNIDADES_id_UNIDADES` ASC) VISIBLE,
  INDEX `fk_CURSOS_TURMAS1_idx` (`TURMAS_id_COD_TURMA` ASC) VISIBLE,
  CONSTRAINT `fk_CURSOS_UNIDADES1`
    FOREIGN KEY (`UNIDADES_id_UNIDADES`)
    REFERENCES `mydb`.`UNIDADES` (`Id_Unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSOS_TURMAS1`
    FOREIGN KEY (`TURMAS_id_COD_TURMA`)
    REFERENCES `mydb`.`TURMAS` (`id_COD_TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `id_Matricula` INT NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `ENDEREÇO_id_ENDEREÇO_PESSOA` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Matricula`),
  INDEX `fk_ALUNO_ENDEREÇO1_idx` (`ENDEREÇO_id_ENDEREÇO_PESSOA` ASC) VISIBLE,
  CONSTRAINT `fk_ALUNO_ENDEREÇO1`
    FOREIGN KEY (`ENDEREÇO_id_ENDEREÇO_PESSOA`)
    REFERENCES `mydb`.`ENDEREÇO` (`id_ENDEREÇO_Pess/unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTRUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTRUTOR` (
  `ID_NOME` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `Dt_nascimento` DATE NOT NULL,
  `ENDEREÇO_id_ENDEREÇO_PESSOA` VARCHAR(10) NOT NULL,
  INDEX `fk_INSTRUTOR_ENDEREÇO1_idx` (`ENDEREÇO_id_ENDEREÇO_PESSOA` ASC) VISIBLE,
  PRIMARY KEY (`ID_NOME`),
  CONSTRAINT `fk_INSTRUTOR_ENDEREÇO1`
    FOREIGN KEY (`ENDEREÇO_id_ENDEREÇO_PESSOA`)
    REFERENCES `mydb`.`ENDEREÇO` (`id_ENDEREÇO_Pess/unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUNO_has_TURMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO_has_TURMAS` (
  `ALUNO_id_Matricula` INT NOT NULL,
  `TURMAS_id_COD_TURMA` VARCHAR(100) NOT NULL,
  `INSTRUTOR_ID_NOME` VARCHAR(100) NOT NULL,
  `Nome_disciplina` VARCHAR(45) NOT NULL,
  INDEX `fk_ALUNO_has_TURMAS_TURMAS1_idx` (`TURMAS_id_COD_TURMA` ASC) VISIBLE,
  INDEX `fk_ALUNO_has_TURMAS_ALUNO1_idx` (`ALUNO_id_Matricula` ASC) VISIBLE,
  INDEX `fk_ALUNO_has_TURMAS_INSTRUTOR1_idx` (`INSTRUTOR_ID_NOME` ASC) VISIBLE,
  CONSTRAINT `fk_ALUNO_has_TURMAS_ALUNO1`
    FOREIGN KEY (`ALUNO_id_Matricula`)
    REFERENCES `mydb`.`ALUNO` (`id_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_has_TURMAS_TURMAS1`
    FOREIGN KEY (`TURMAS_id_COD_TURMA`)
    REFERENCES `mydb`.`TURMAS` (`id_COD_TURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_has_TURMAS_INSTRUTOR1`
    FOREIGN KEY (`INSTRUTOR_ID_NOME`)
    REFERENCES `mydb`.`INSTRUTOR` (`ID_NOME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
